local opt = vim.opt

opt.clipboard = "unnamedplus"
opt.completeopt = "menuone,noselect"
opt.expandtab = true
opt.hidden = true
opt.ignorecase = true
opt.incsearch = true
opt.list = true
opt.listchars = "tab:»·,trail:·,extends:→,precedes:←"
opt.mouse = "a"
opt.number = true
opt.relativenumber = true
opt.shiftwidth = 2
opt.shortmess:append("c")
opt.showmode = false
opt.smartcase = true
opt.smartindent = true
opt.splitbelow = true
opt.splitright = true
opt.tabstop = 2
opt.termguicolors = true
opt.undofile = true
opt.updatetime = 300
opt.wrap = false
opt.wrapscan = true
opt.writebackup = false
opt.swapfile = false
opt.backup = false
opt.undodir = vim.fn.stdpath("data") .. "/undo"
opt.undolevels = 1000
opt.undoreload = 10000
opt.scrolloff = 8
opt.sidescrolloff = 8
opt.signcolumn = "auto"
opt.cursorline = true
opt.foldmethod = "expr"
opt.foldexpr = "v:lua.vim.treesitter.foldexpr()"
opt.foldtext = "v:lua.vim.treesitter.foldtext()"
opt.foldlevel = 99
opt.foldnestmax = 10
opt.foldminlines = 1
opt.foldcolumn = "auto"
opt.hlsearch = true
opt.inccommand = "nosplit"
